version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    deploy:
      replicas: 3
  
  service1:
    container_name: service1
    image: ngww/service1
    build: ./service1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment: 
      DATABASE_URI: "mysql+pymysql://root:ZaneleN11@35.197.221.222:3306/fortunes"
      TEST_DATABASE_URI: "mysql+pymysql://root:ZaneleN11@35.197.221.222:3306/test_fortunes"
    deploy:
      replicas: 3
  service2:
    image: ngww/service2
    build: ./service2
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
      replicas: 3
  service3:
    image: ngww/service3
    build: ./service3
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
      replicas: 3
  service4:
    image: ngww/service4
    build: ./service4
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy:
      replicas: 3

  database:
    image: mysql:5.7
    ports:
    - target: 3306
      published: 3306
    environment:
      MYSQL_ROOT_PASSWORD: ZaneleN11
      MYSQL_DATABASE: sfia2
    volumes:
    - type: volume
      source: database-volume
      target: /var/lib/mysql

volumes: 
  database-volume: