---
# hostvars lets you access variables for another host
- name: Add worker to manager node
  shell: docker swarm join --token {{ hostvars['w_token']['value'] }} {{ hostvars['m_hostname']['value'] }}:2377
  ignore_errors: true    